export const environment = {
    production: false,
    APP: {
        API_URL: APIURL,
        // PANELS LINKS
        PARENT_PANEL: 'https://parentsylvandemo.clicklabs.in/',
        ONBOARD_PANEL: 'https://signinsylvandemo.clicklabs.in/',
        TUTOR_PANEL: 'https://tutorsylvandemo.clicklabs.in/',
        LEAD_GEN: 'https://18.222.79.2/sylvan-wordpress/',
        // profile api
        PARENT_PROFILE: '/api/v1/parent/accessTokenLogin',
        UPDATE_PARENT_PROFILE: '/api/v1/parent/editProfile',
        CONFIRM_SIGNUP_OTP_API: '/api/v1/parent/verifyPhoneNumber',
        CHECK_TUTOR_AVAILABILITY: '/api/v1/booking/checkTutorAvailability',
        RESEND_OTP_API: '/api/v1/parent/resendOtpEmail',
        CHANGE_PASSWORD: '/api/v1/parent/changePassword',
        ADD_ADDRESS: '/api/v1/parent/addAddress',
        ADD_CHILD: '/api/v1/parent/student',
        EDIT_CHILD: '/api/v1/parent/student/',
        DELETE_CHILD: '/api/v1/parent/student/',
        DELETE_ADDRESS: '/api/v1/parent/deleteAddress/',
        BROWSE_TUTOR: '/api/v1/booking/browseTutors?locationDetails=',
        GET_COUNT: '/api/v1/booking/browseTutorsCount?locationDetails=',
        BROWSE_TUTOR_MARKET: '/api/v1/booking/browseTutors',
        GET_COUNT_MARKET: '/api/v1/booking/browseTutorsCount',
        // client keysss:
        GET_LAT_LONG: 'https://www.zipcodeapi.com/rest/js-6bbcxrbtvhIkg1xnwZq26nNxKk2ppOhgvHs7y3eAJevBJl6h9JJaonb5ZhxST6yS/info.json/', //sylvan
        // my dev key:
        // GET_LAT_LONG: 'https://www.zipcodeapi.com/rest/js-uNS3h42OwJSnh2tpOQeucYcbsp8dcu8wVoQZXWR6zxgqMaRsModbUuxO1ngwA6G2/info.json/', //sylvan
        GET_TUTOR_DETAILS: '/api/v1/booking/getTutorById',
        LOGIN: '/api/v1/parent/login',
        GET_TUTOR_DETAILS_BY_UID: '/api/v1/booking/getTutorByUId',

        GET_TUTOR_ADDRESS_STUDENTS: '/api/v1/parent/addressesAndStudents',
        GET_TUTOR_RATINGS: '/api/v1/booking/getTutorRatings',
        GET_TUTOR_RATINGS_BY_UID:'/api/v1/booking/getTutorRatingsByUId',
        RATINGS_COUNT: '/api/v1/booking/getTutorRatingsCount',
        RATINGS_COUNT_BY_UID:'/api/v1/booking/getTutorRatingsCountByUId',
        GET_SUBJECTS: '/api/v1/admin/getSubjects',
        GET_TUTOR_SUBJECTS: '/api/v1/booking/getTutorSubjects',
        GET_ALL_SESSIONS: '/api/v1/booking/getBookings',
        INVOICE_LIST: '/api/v1/invoice/getBookings',
        INVOICE_COUNT: '/api/v1/invoice/bookingsCount',
        GET_BOOKING_BY_ID: '/api/v1/booking/getBookingById',
        GET_NOTIFICATION_BY_ID: '/api/v1/notifications/getNotificationById',
        GET_CANCELLATOIN_POLICY: '/api/v1/admin/getCancellationPolices',
        RATE_AND_APPROVE: '/api/v1/booking/completeBooking/',
        FEEDBACK_TUTOR: '/api/v1/booking/rateTutor/',
        CANCEL_BOOKING_BY_ID: '/api/v1/booking/cancelBookingByParent',
        CANCEL_TUTOR_BOOKING_BY_ID:'/api/v1/booking/acceptRejectByParent',
        CHECK_AVAILBILITY_OF_PROMOCODES: '/api/v1/booking/currentPromocodes',
        // CREATE_BOOKING: '/api/v1/booking/createBooking',
        CREATE_BOOKING: '/api/v1/booking/createBookings',
        RESCHEDULE_BOOKING: '/api/v1/booking/rescheduleRequestByParent/',
        REGISTER_API: '/parent/register',
        CONTACT_API: '/api/v1/admin/contact',
        CONTACT_TUTOR_API: '/api/v1/twilio/sendMessage',
        DISPUTE_API: '/api/v1/booking/raiseDispute',
        LOGOUT_API: '/api/v1/parent/logout',
        ALL_DISPUTES: '/api/v1/parent/disputes',
        DISPUTE_BY_ID: '/api/v1/parent/getDisputeById',
        GET_SESSION_REPORTS: '/api/v1/parent/getSessionFeedback',
        GET_SESSION_REPORTS_COUNT: '/api/v1/parent/sessionFeedbackCount',
        GET_DISPUTES_COUNT: '/api/v1/parent/disputesCount',
        // DISPUTE_COUNT:''
        GET_BOOKING_COUNT: '/api/v1/booking/bookingsCount',
        APPLY_PROMOCODE: '/api/v1/booking/applyPromocode',
        GET_ALL_NOTIFICATION: '/api/v1/notifications/getNotifications',
        SEE_ALL_NOTIFICATION: '/api/v1/notifications/readNotifications',
        READ_NOTIFICATION: '/api/v1/notifications/readNotification/',
        FORGOT_API: '/api/v2/web/user/forgotPassword',
        FORGOT_OTP_API: '/api/v2/web/user/verifyOtpWeb',
        RESET_PASSWORD_API: '/api/v2/web/user/resetPasswordWeb',
        ACCEPT_REJECT_BOOKING: '/api/v1/booking/rescheduleAcceptReject/',
        REGISTER_ADDRESS_API: '/api/v2/web/user/register/step2',
        REGISTER_DOCUMENTS_API: '/api/v2/web/user/register/step3',
        SEND_VERIFICATION_TYPE_API: '/api/v2/web/user/register/step4',
        EDIT_ADDRESS: '/api/v1/parent/editAddress/',
        CHANGE_PHONE_NUMBER_API: '/api/v2/web/user/register/changePhoneNumber',
        CHANGE_EMAIL_API: '/api/v2/web/user/register/changeEmail',
        FAQ: '/api/v1/admin/getConstants',
        GET_REFFERAL: '/api/v1/booking/parentReferralDiscounts',
        CHECK_BOOKINGS: '/api/v1/parent/anyUpcomingSession',
        CHECK_TUTOR_LIVE:'/api/v1/booking/checkTutorIsLive',
        // GET_USER_DETAILS_API: '/api/v2/web/user/detailsById',
        GET_ALL_CATEGORIES: '/api/v1/category',
        GET_ALL_SUB_CATEGORIES: '/api/v1/subCategory',
        POST_JOB: '/api/v2/webJobs/postJobs',
        GET_ALL_POSTS: '/api/v2/webJobs/myPostsWeb',
        GET_POST: '/api/v2/webJobs/jobById',
        GET_LABORS: '/api/v2/webJobs/getLaboursWeb',
        GET_ALL_JOBS_POSTS: '/api/v2/webJobs/jobSearch',
        GET_ALL_LABORS: '/api/v2/webJobs/laborSearch',
        GET_ALL_FEEDBACKS: '/api/v1/user/myRatings',
        CHANGE_PAYMENT_MODE: '/api/v1/booking/changePaymentMethod/',
        CHANGE_CARD_FOR_UPCOMING: '/api/v1/booking/changePaymentMethodForUpcomingSessions',
        GET_ALL_BOOKING: '/admin/getAllAvailabeBooking',
        GET_ALL_OUTGOING_BOOKING: '/admin/getOngoingBooking',
        GET_ALL_PAST_BOOKING: '/admin/getPastBooking',
        // GET_BOOKING_BY_ID: '/admin/getBookingDetails',
        // CANCEL_BOOKING_BY_ID: '/admin/cancelBooking',

        GET_ALL_USER: '/admin/getAllUsers',
        GET_USER: '/admin/userDetails',
        GET_ALL_USER_BY_ID: '/admin/userDetails',
        BLOCK_USER_BY_ID: '/admin/blockOption',
        DELETE_USER_BY_ID: '/admin/deleteUser',
        REGISTER_SERVICE: '/admin/serviceProvider/register',
        EDIT_USER_BY_ID: '/admin/userDetails/',
        ADD_CUSTOMER: '/admin/customer/registerFromEmail',
        ADD_DRIVER: '/admin/driver/registerFromEmail',
        EDIT_USER_BY_ID_SUCCESS: '/admin/customer/updateProfile',
        EDIT_SERVICE_BY_ID: '/admin/userDetails/',
        EDIT_SERVICE_BY_ID_SUCCESS: '/admin/serviceProvider/updateProfile',
        REGISTER_CUSTOMER: '/admin/customer/registerFromEmail',
        REGISTER_DRIVER: '/admin/driver/registerFromEmail',
        EDIT_DRIVER_BY_ID_SUCCESS: '/admin/driver/updateProfile',

        GET_DASHBOARD_COUNT: '/admin/getDashboardCount',


        CLEAR_ALL_NOTIFICATION: '/notification/admin/clearNotification',

        SETTINGS_KEY_MESSAGE: '/multilingual/addResourceBundle',

        EDIT_WORKER_BY_ID_SUCCESS: '/admin/worker/updateProfile',
        CHANGE_WORKER_DOCUMENT_APPROVAL: '/admin/worker/changeApprovalStatus',
        GET_SERVICE_RADII: '/admin/getDefaultSettings',
        SET_SERVICE_RADII: '/admin/setDefaultSettings',

        SET_QUALIFICATION: '/universalVariables/addNewQualification',
        UPDATE_QUALIFICATION: '/universalVariables/updateQualification',
        GET_EXPERTISE: '/universalVariables/getAllExpertise',
        GET_EQUIPMENTS: '/admin/machine',
        SET_EXPERTISE: '/universalVariables/addNewExpertise',
        ADD_MACHINE: '/admin/machine',
        UPDATE_MACHINE: '/universalVariables/updateMachine',
        UPDATE_EXPERTISE: '/universalVariables/updateExpertise',

        GET_ALL_SUBSCRIPTIONS: '/admin/getSubscription',
        GET_SUBSCRIPTION: '/admin/getSubscription',
        BLOCK_SUBSCRIPTION: '/admin/deleteSubscription',
        UPDATE_SUBSCRIPTION: '/admin/updateSubscription',
        ADD_SUBSCRIPTION: '/admin/subscription',

        EDIT_EMPLOYER_BY_ID_SUCCESS: '/admin/emp/updateProfile',
        ADD_EMPLOYER: '/admin/employer/registerFromEmail',
        ADD_WORKER: '/admin/worker/registerFromEmail',
        APPROVE_USER_BY_ID: '/admin/verifyUser',
        REJECT_USER_BY_ID: '/admin/rejectUserDocs',
        CHANGE_EMPLOYER_DOCUMENT_APPROVAL: '/admin/emp/changeApprovalStatus',

        GET_ALL_JOBS: '/admin/getAllJobs',

        UPLOAD_FILE: '/user/uploadFile',
        UPLOAD_MULTIPLE_FILES: '/user/uploadMultipleFiles',
        //Schedular
        SET_AVAILABILTY: '/api/v1/tutor/setAvailability',
        GET_AVAILABILTY: '/api/v1/tutor/getAvailability',
        GET_AVAILABILTY_DAYS:'/api/v1/booking/getAvailableDates',

        //Payments
        ADD_CARD_API: '/api/v1/parent/addCard',
        DELETE_CARD_API: '/api/v1/parent/deleteCard',
        DEFAULT_CARD_API: '/api/v1/parent/setDefaultCard',
        UPDATE_CARD_API: '/api/v1/parent/updateCard',
        GENERATE_PDF: '/api/v1/invoice/generatePDF',
        STUDENT_LIST: '/api/v1/parent/getStudents',
        STUDENT_UPCOMING_SESSION: '/api/v1/parent/studentUpcomingSession',

    },

    ERROR: {
        NAME_INVALID: 'Only A-Z/a-z allowed',
        PASSWORD_INVALID: 'Password is invalid (minimum eight characters, at least one uppercase letter, one lowercase letter and one number)'
    }
};
